# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\x12\x08\x64ocument\"u\n\ruploadRequest\x12\x13\n\x0bidRemitente\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tcontenido\x18\x03 \x01(\t\x12\x15\n\rcantidadNodos\x18\x04 \x01(\t\x12\x15\n\rpuertoEscucha\x18\x05 \x01(\t\"?\n\x0euploadResponse\x12\x13\n\x0bidRemitente\x18\x01 \x01(\t\x12\x18\n\x10mensajeRespuesta\x18\x02 \x01(\t\"d\n\x0f\x64ownloadRequest\x12\x13\n\x0bidRemitente\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x15\n\rcantidadNodos\x18\x03 \x01(\t\x12\x15\n\rpuertoEscucha\x18\x04 \x01(\t\"J\n\x10\x64ownloadResponse\x12\x13\n\x0bidRemitente\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tcontenido\x18\x03 \x01(\t\"h\n\x0blistRequest\x12\x13\n\x0bidRemitente\x18\x01 \x01(\t\x12\x16\n\x0eidDestinatario\x18\x02 \x01(\t\x12\x15\n\rcantidadNodos\x18\x03 \x01(\t\x12\x15\n\rpuertoEscucha\x18\x04 \x01(\t\".\n\tDocumento\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tcontenido\x18\x02 \x01(\t\"L\n\x0clistResponse\x12\x13\n\x0bidRemitente\x18\x01 \x01(\t\x12\'\n\ndocumentos\x18\x02 \x03(\x0b\x32\x13.document.Documento2\xe5\x01\n\x0f\x44ocumentService\x12\x44\n\x0f\x63\x61rgarDocumento\x12\x17.document.uploadRequest\x1a\x18.document.uploadResponse\x12K\n\x12\x64\x65scargarDocumento\x12\x19.document.downloadRequest\x1a\x1a.document.downloadResponse\x12?\n\x0elistarRecursos\x12\x15.document.listRequest\x1a\x16.document.listResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=28
  _globals['_UPLOADREQUEST']._serialized_end=145
  _globals['_UPLOADRESPONSE']._serialized_start=147
  _globals['_UPLOADRESPONSE']._serialized_end=210
  _globals['_DOWNLOADREQUEST']._serialized_start=212
  _globals['_DOWNLOADREQUEST']._serialized_end=312
  _globals['_DOWNLOADRESPONSE']._serialized_start=314
  _globals['_DOWNLOADRESPONSE']._serialized_end=388
  _globals['_LISTREQUEST']._serialized_start=390
  _globals['_LISTREQUEST']._serialized_end=494
  _globals['_DOCUMENTO']._serialized_start=496
  _globals['_DOCUMENTO']._serialized_end=542
  _globals['_LISTRESPONSE']._serialized_start=544
  _globals['_LISTRESPONSE']._serialized_end=620
  _globals['_DOCUMENTSERVICE']._serialized_start=623
  _globals['_DOCUMENTSERVICE']._serialized_end=852
# @@protoc_insertion_point(module_scope)
