# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import document_pb2 as document__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cargarDocumento = channel.unary_unary(
                '/document.DocumentService/cargarDocumento',
                request_serializer=document__pb2.uploadRequest.SerializeToString,
                response_deserializer=document__pb2.uploadResponse.FromString,
                _registered_method=True)
        self.descargarDocumento = channel.unary_unary(
                '/document.DocumentService/descargarDocumento',
                request_serializer=document__pb2.downloadRequest.SerializeToString,
                response_deserializer=document__pb2.downloadResponse.FromString,
                _registered_method=True)
        self.listarRecursos = channel.unary_unary(
                '/document.DocumentService/listarRecursos',
                request_serializer=document__pb2.listRequest.SerializeToString,
                response_deserializer=document__pb2.listResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cargarDocumento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def descargarDocumento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listarRecursos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cargarDocumento': grpc.unary_unary_rpc_method_handler(
                    servicer.cargarDocumento,
                    request_deserializer=document__pb2.uploadRequest.FromString,
                    response_serializer=document__pb2.uploadResponse.SerializeToString,
            ),
            'descargarDocumento': grpc.unary_unary_rpc_method_handler(
                    servicer.descargarDocumento,
                    request_deserializer=document__pb2.downloadRequest.FromString,
                    response_serializer=document__pb2.downloadResponse.SerializeToString,
            ),
            'listarRecursos': grpc.unary_unary_rpc_method_handler(
                    servicer.listarRecursos,
                    request_deserializer=document__pb2.listRequest.FromString,
                    response_serializer=document__pb2.listResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cargarDocumento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/cargarDocumento',
            document__pb2.uploadRequest.SerializeToString,
            document__pb2.uploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def descargarDocumento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/descargarDocumento',
            document__pb2.downloadRequest.SerializeToString,
            document__pb2.downloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listarRecursos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/listarRecursos',
            document__pb2.listRequest.SerializeToString,
            document__pb2.listResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
